### PR TITLE
added the macro WITH-STATIC-VECTORS

### PR DESCRIPTION
**Pull request by marcoheisig**
Hi Stelian,

would it be possible to add a macro WITH-STATIC-VECTORS for the power users?

Best regards,
Marco

### CODE REVIEW

**Comment by sionescu** [comment]
In what sense is this for power users ?

**Comment by marcoheisig** [comment]
I write a lot of distributed software with message passing, where I often need a fixed number of message buffers to communicate with the nearest neighbors. In this case it is a little bit ugly to write about six nested WITH-STATIC-VECTOR invocations.

Actually the WITH-STATIC-VECTORS macro is already part of cl-mpi, but I thought it would make more sense to have it directly in the static-vectors project.

**Comment by sionescu** [comment]
Committed a slightly different implementation. Thank you.

**Comment by marcoheisig** [comment]
OMG, thank you! Damn, now I feel like I should release a new version of cl-mpi :)

**Pull request closed without merging**
